name: test with dune pkg

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Check out sources
      uses: actions/checkout@v6
    - name: Install and test
      uses: Leonidas-from-XIV/setup-dune@4f07728051a3b72713b8174eaa2424d6ce94da25
